# .github/workflows/douban.yml
name: douban
on: 
  schedule:
  - cron: "15 * * * *"

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 175157765
        type: movie
        format: neodb
        neodb_token: ${{ secrets.neodb_token }}
        
    - name: music
      uses: lizheming/doumark-action@master
      with:
        id: 175157765
        type: music
        format: neodb
        neodb_token: ${{ secrets.neodb_token }}

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 175157765
        type: music
        format: neodb
        neodb_token: ${{ secrets.neodb_token }}
